apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spa
  template:
    metadata:
      labels:
        app: spa
    spec:
      containers:
      - name: spa
        image: myacrregistry.azurecr.io/spa:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: spa
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: spa

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: myacrregistry.azurecr.io/auth:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: auth

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - name: service3
        image: myacrregistry.azurecr.io/service3:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service3
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: service3
